"""init

Revision ID: 72a35d23af28
Revises: 9f7580fcebc9
Create Date: 2022-03-03 20:07:10.074214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a35d23af28'
down_revision = '9f7580fcebc9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
