"""init

Revision ID: 9f7580fcebc9
Revises: 
Create Date: 2022-03-03 20:06:16.897085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7580fcebc9'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserModel',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_UserModel'))
    )
    op.create_index(op.f('ix_UserModel_email'), 'UserModel', ['email'], unique=True)
    op.create_index(op.f('ix_UserModel_id'), 'UserModel', ['id'], unique=False)
    op.create_index(op.f('ix_UserModel_name'), 'UserModel', ['name'], unique=False)
    op.create_table('UserDetails',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('emp_code', sa.Integer(), nullable=True),
    sa.Column('phone_no', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('user_incharge_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserModel.id'], name=op.f('fk_UserDetails_user_id_UserModel')),
    sa.ForeignKeyConstraint(['user_incharge_id'], ['UserModel.id'], name=op.f('fk_UserDetails_user_incharge_id_UserModel')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_UserDetails'))
    )
    op.create_index(op.f('ix_UserDetails_emp_code'), 'UserDetails', ['emp_code'], unique=False)
    op.create_index(op.f('ix_UserDetails_id'), 'UserDetails', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserDetails_id'), table_name='UserDetails')
    op.drop_index(op.f('ix_UserDetails_emp_code'), table_name='UserDetails')
    op.drop_table('UserDetails')
    op.drop_index(op.f('ix_UserModel_name'), table_name='UserModel')
    op.drop_index(op.f('ix_UserModel_id'), table_name='UserModel')
    op.drop_index(op.f('ix_UserModel_email'), table_name='UserModel')
    op.drop_table('UserModel')
    # ### end Alembic commands ###
